version: '3.1'

services:

  postgres-db:
    image: postgres
    restart: always
    container_name: monar2-postgres-db
    volumes:
      - ../postgresdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"